# Generated by Django 2.1.4 on 2019-01-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='album',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='album_picture',
            field=models.TextField(null=True),
        ),
    ]
