# Generated by Django 2.1.4 on 2019-01-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab4', '0002_auto_20190115_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songcomment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
